### ISSUE TITLE
Segmentation fault (core dumped) when start with new user profile

### ISSUE THREAD

**Issue by martinkg** [MBach/Miam-Player#113]
start with a new user profile or delete the application settings with:
[martin@fc25 ~]$ cd ~/.config/; rm -rf QtProject.conf dconf MmeMiamMiam

[martin@fc25 ~]$ miam-player
QtAV 1.11.0(Oct 17 2016, 09:27:08)
Multimedia framework base on Qt and FFmpeg.
Distributed under the terms of LGPLv2.1 or later.
Shanghai University->S3 Graphics->Deepin, Shanghai, ChinaCopyright (C) 2012-2016 Wang Bin (aka. Lucas Wang) wbsecg1@gmail.com
Donate: http://qtav.org/donate.html
Source: https://github.com/wang-bin/QtAV
Home page: http://qtav.org

reproduce:
Step1: click here to manually search for music
Step2: Add location
Step3: Close the window with the title "Customize general options"
then "Segmentation fault (core dumped)" occurs.

**Comment by MBach** [comment]
Hmm, that will be hard to debug! I don't have much informations to help me:

    Thread 1 "miam-player" received signal SIGSEGV, Segmentation fault.
    0x00007ffff5c1f743 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib64/libQt5Core.so.5

**Comment by martinkg** [comment]
thats true, when debugging with gdb I can't enter backtrace (bt).

**Comment by MBach** [comment]
OK this wasn't easy to find, but I suspected a problem with QuickStart. Should be fixed with latest commit: https://github.com/MBach/Miam-Player/commit/83bfdcfeed319700a0400dd5951346cc83ffafbe

Unfortunately, I've discovered a small race condition when there are very little tracks to scan and when the scan is finished before the view is fully initialized:

![race_condition](https://cloud.githubusercontent.com/assets/1532657/22667388/d6138536-ecbc-11e6-9289-17c408a79d1b.png)

**Comment by MBach** [comment]
Last commit https://github.com/MBach/Miam-Player/commit/e32969c7b381b38291108324ddec753cf9cc1150 should not produce the screenshot any more! I think this issue is ready to be closed.

**Comment by martinkg** [comment]
works now again, without problems, thanks.
