### ISSUE TITLE
Add opus encoder support

### ISSUE THREAD

**Issue by Ilya87** [MBach/Miam-Player#34]
Now Miam-Player doesn't support opus codec. Add support for it, please.

**Comment by MBach** [comment]
Preliminary support in commit https://github.com/MBach/Miam-Player/commit/da490cc6802415eae0728b9916e2aeda6be57e2b

**Comment by Ilya87** [comment]
What did you mean by "preliminary"? My .opus files are decoded, I can change their tags, but for one (at least) file file I still see "error reading..." bug and can't seek them by clicking to seek panel
https://yadi.sk/d/wHm_rd2gfaBc9 - file that can't be scanned.

**Comment by MBach** [comment]
Well, again, it's an encoding problem with Linux platform! It's working fine on Windows and that's really starting to piss me off :)

![decoding_opus](https://cloud.githubusercontent.com/assets/1532657/6880423/93734aae-d530-11e4-94db-4a6cdead5965.png)

About seeking into Opus files, you are correct: it's not working with the SeekBar but seek buttons seems to be OK. That's why I said "preliminary" support. Because seeking in Opus files works in VLC Media Player, but not really in Miam-Player. I have these messages in the console:

`[000000d9b3782560] ogg demux error: No selected seekable stream found
core input error: INPUT_CONTROL_SET_POSITION(_OFFSET) 17.0% failed
[000000d9b3761880] core input error: INPUT_CONTROL_SET_POSITION(_OFFSET) 17.0% failed
ogg demux error: No selected seekable stream found
[000000d9b3782560] ogg demux error: No selected seekable stream found
core input error: INPUT_CONTROL_SET_POSITION(_OFFSET) 18.5% failed
[000000d9b3761880] core input error: INPUT_CONTROL_SET_POSITION(_OFFSET) 18.5% failed`

Pay attention that's it's also the same problem for seeking in OGG files in general, not Opus only.

**Comment by Ilya87** [comment]
With fixing #32 I should close this issue.
