### ISSUE TITLE
Shuffle-Mode

### ISSUE THREAD

**Issue by Zoba273** [MBach/Miam-Player#70]
It would be nice to have a shuffle mode for playlists as a default button instead only in the main menu:

Like this but toggable http://i.imgur.com/dd2000r.png

Also, shuffle shouldn't play the same song twice.

**Comment by MBach** [comment]
Hello @Zoba273 

In fact there's already a Shuffle Mode button, but there is a small bug when the Oxygen Theme isn't selected. Shuffle icon is missing for some themes, so a fallback mode must be implemented, to display a default picture.

Shuffle Mode already plays music in a random mode where the same song will not be played twice. But this is valid when you're playlist isn't over. When you have reached the end, of course playback will start a second time with the same order as the first play. So this is not a complete random every time track is changing because it's very annoying for the user to listen the same track twice in a row.

**Comment by MBach** [comment]
Done in https://github.com/MBach/Miam-Player/commit/0f050ce2e4a7f4d6d17b44d8563e6fdf02a9c5c8
