### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by Ilya87** [MBach/Miam-Player#73]
Compilation fails on Linux due to case sensitiveness: library.qrc Cannot find file 'translations/Library_en.qm'. «Library» should be «library».

**Comment by MBach** [comment]
Hi @Ilya87 
I'm aware of this. I made major changes since a few commits. I have reorganized the project structure and lots of views (and their translations) are moving to other folders. Maybe you have noticed it, but right now startup time has been widely improved! 

However, I haven't finished to reconnect things. Also, I would like to close old issues before the next release.

**Comment by Ilya87** [comment]
I think startup time was quite fast before update. Thank you in advance.

**Comment by MBach** [comment]
I have fixed the build and moved parts of translation into new files. Some review need to be done for Russian language.

**Comment by Ilya87** [comment]
I already noticed this. Be soon.
