### ISSUE TITLE
Playlist double click error

### ISSUE THREAD

**Issue by Ilya87** [MBach/Miam-Player#76]
When I make a double click on playlist's track the next to him track in the list starts playing.

**Comment by MBach** [comment]
Yes I know... I've made major changes with the core functionalities in order to have a working Playlist Mode and a working Unique Library Mode. 

For example, currently in the Unique Mode, when a track has finished to play, next one doesn't start automatically, player is crashing when you're switching mode if one track is playing, track aren't well sorted (01, 10, 11, 02, 03, 04, ...), plugins are not working any more because of the new Lazy loading mode, etc.

**Comment by MBach** [comment]
Hello @Ilya87 
https://github.com/MBach/Miam-Player/commit/c17d2a3570e685333120002d4ef675eab51b3afc should fix this issue.
Also works on the Unique Mode: I've made big changes and it's almost finished for this view.
